delete:
	rm -rf ./CollectionsDump/KANBACK.json
	rm -rf ./CollectionsDump/KANBG.json
	rm -rf ./CollectionsDump/KANCHEST.json
	rm -rf ./CollectionsDump/KANFRNT.json
	rm -rf ./CollectionsDump/KANHAND.json
	rm -rf ./CollectionsDump/KANHEAD.json
