delete:
	rm -rf ./CollectionsDump/KANBACK.json
	rm -rf ./CollectionsDump/KANBG.json
	rm -rf ./CollectionsDump/KANCHEST.json
	rm -rf ./CollectionsDump/KANFRNT.json
	rm -rf ./CollectionsDump/KANHAND.json
	rm -rf ./CollectionsDump/KANHEAD.json
	rm -rf ./CollectionsDump/EVNTS.json
	rm -rf ./CollectionsDump/KANF.json
	rm -rf ./CollectionsDump/KANL.json
	rm -rf ./CollectionsDump/KANR.json
	rm -rf ./CollectionsDump/KANS.json
